easy_admin:
    entities:
        # change the following to the namespaces of your own entities
        - App\Entity\Stage
        - App\Entity\Formation
        - App\Entity\Entreprise
        - App\Entity\User

    site_name: 'Pro<i>Stages</i>'
    design:
      brand-color: '#78c2ad'
      assets:
            css:
                - 'css/admin.css'

    list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: '' }
                    - { name: 'delete', icon: 'trash', label: '' }